# Generated by Django 4.2.3 on 2023-07-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players_characters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerscharacters",
            name="character_sheet_url",
            field=models.CharField(
                blank=True,
                max_length=1080,
                null=True,
                verbose_name="Url fiche de personnage",
            ),
        ),
        migrations.AlterField(
            model_name="playerscharacters",
            name="player",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nom du Joueur"
            ),
        ),
    ]
