# Generated by Django 4.2.3 on 2023-07-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Regions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=240, verbose_name="Nom de la région"),
                ),
                (
                    "visited",
                    models.BooleanField(default=False, verbose_name="Déjà visitée"),
                ),
                (
                    "religion",
                    models.CharField(
                        blank=True,
                        max_length=240,
                        null=True,
                        verbose_name="Religion principale",
                    ),
                ),
                (
                    "politic",
                    models.CharField(
                        blank=True,
                        max_length=240,
                        null=True,
                        verbose_name="Sytème politique",
                    ),
                ),
                (
                    "chief",
                    models.CharField(
                        blank=True, max_length=240, null=True, verbose_name="Chef connu"
                    ),
                ),
                (
                    "region_maps_url",
                    models.CharField(
                        blank=True,
                        max_length=240,
                        null=True,
                        verbose_name="Lien vers la carte",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "history_in_campaign",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Activité importante lié à la campagne",
                    ),
                ),
            ],
        ),
    ]
